### ISSUE TITLE
HWND not found

### ISSUE THREAD

**Issue by GeorgHoffmeyer** [benpye/wsl-ssh-pageant#23]
Hi,
when I try to use ssh on wsl I get the following error:
```
WSL AF_UNIX socket listening on c:\Tools\wsl-ssh-pageant\sock\ssh-agent.sock
WslSSHPageant.PageantException: HWND not found
   at WslSSHPageant.PageantHandler.Query(ArraySegment`1 buf) in C:\projects\wsl-ssh-pageant\PageantHandler.cs:line 115
   at WslSSHPageant.SSHAgentClient.<ServiceSocket>d__7.MoveNext() in C:\projects\wsl-ssh-pageant\SSHAgentClient.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WslSSHPageant.SSHAgentClient.<WorkSocket>d__6.MoveNext() in C:\projects\wsl-ssh-pageant\SSHAgentClient.cs:line 57
^C
c:\Tools\wsl-ssh-pageant>wsl-ssh-pageant.exe --wsl c:\Tools\wsl-ssh-pageant\sock\ssh-agent.sock
WSL AF_UNIX socket listening on c:\Tools\wsl-ssh-pageant\sock\ssh-agent.sock
WslSSHPageant.PageantException: HWND not found
   at WslSSHPageant.PageantHandler.Query(ArraySegment`1 buf) in C:\projects\wsl-ssh-pageant\PageantHandler.cs:line 115
   at WslSSHPageant.SSHAgentClient.<ServiceSocket>d__7.MoveNext() in C:\projects\wsl-ssh-pageant\SSHAgentClient.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WslSSHPageant.SSHAgentClient.<WorkSocket>d__6.MoveNext() in C:\projects\wsl-ssh-pageant\SSHAgentClient.cs:line 57
```

**Comment by benpye** [comment]
Hey,

Looks like you're using the older C# version, but it should still work.

Few questions:

1. What are you using to provide Pageant? (Pageant, gpg4win, etc)
2. What user are you running Pageant as, what user are you running wsl-ssh-ageant as?
3. Does PuTTy work?

**Comment by benpye** [comment]
@GeorgHoffmeyer I don't suppose you've had a chance to look at this?

**Comment by benpye** [comment]
I'm gonna close this out - @GeorgHoffmeyer if you hit this again please reopen!
